name: option_result
description: A lightweight Dart library for Rust-like Option/Result types. Supports exhaustive pattern matching and provides helpers for None()/Err() propagation
version: 3.1.2
repository: https://github.com/zajrik/option_result
issue_tracker: https://github.com/zajrik/option_result/issues

topics:
  - option
  - result
  - pattern-matching

environment:
  sdk: ^3.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
