name: option_result
description: A simple Dart library for Rust-like Result/Option types
version: 0.0.1-dev-1
repository: https://github.com/zajrik/option_result

environment:
  sdk: ^3.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
