name: option_result
description: A lightweight Dart library for Rust-like Option/Result types. Supports exhaustive pattern matching and provides helpers for None()/Err() propagation
version: 0.0.1-dev-2
repository: https://github.com/zajrik/option_result

environment:
  sdk: ^3.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
